name: Art Portfolio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#b0b0b0'
    - '#797979'
    - '#272727'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
