name: Stacie Arellano - Portfolio
favicon: null
layout_spectrum: 0.50585
typography_spectrum: 0.85677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6beaa'
    - '#fdfcfc'
    - '#b77059'
    - '#773720'
    - '#120d14'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
