name: Stacie Arellano - Portfolio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcf7'
    - '#343635'
    - '#939592'
    - '#e34143'
    - '#f1acaf'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
