typography_spectrum: 0.6459032144190947
color:
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  brandStrength: 0.448772570052009
  lightness: 0.15707781184141956
  saturation: 0.3795490725655662
  rhythmicContrast: 0.1302773301860336
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8990358274905841
analytics:
  google: UA-78516-16
  facebook: null
  twitter: null
author:
  name: Stacie Arellano
  email: stacie@staciearellano.com
  url: 'http://www.staciearellano.com'
name: Stacie Arellano
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
  - name: Portraits
    id: a719412c-2d4d-4f94-b820-83d598a50386
    type: content
  - name: Linocuts
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Print shop
    url: 'https://squareup.com/store/staciearellano'
    type: external
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
favicon: null
title: Ink Love
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2a9a741-02b8-4653-8f25-e06f9bbf7fa3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2a9a741-02b8-4653-8f25-e06f9bbf7fa3.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: 'Comics, Linocuts, Illustrations and joy from Stacie Arellano.'
purpose:
  - type: external
    url: 'https://squareup.com/store/staciearellano'
    label: Buy Original Art
  - type: external
    url: 'https://www.createspace.com/4959420'
    label: Buy Graphic Novel
