layout_spectrum: 0.18967789946889302
typography_spectrum: 0.7084992472640248
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3832073469223953
  lightness: 0.5467448191261749
  saturation: 0.42776037637208875
  rhythmicContrast: 0.7258910972692331
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-78516-16
  facebook: null
  twitter: null
name: Stacie Arellano
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
  - name: Linocuts
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
favicon: null
title: Ink Love
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FPUEMsou2r-w%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPUEMsou2r-w&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FPUEMsou2r-w%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Stacie Arellano
          url: 'https://www.youtube.com/user/Metahar1'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - duration
        - manga
        - views
        - studio
        - kluser
        - ccmixter
        - arellano
        - stacie
        - comic
        - shogunroninartist
      description: >-
        Check out my adventure comic on http://www.tributewaters.com I'm working
        in Manga Studio here. Music:
        http://ccmixter.org/files/geertveneklaas/23254
        http://ccmixter.org/files/waldhorn33/11246
        http://ccmixter.org/files/Loveshadow/23570 (less info)
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=PUEMsou2r-w&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=PUEMsou2r-w&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=PUEMsou2r-w&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=PUEMsou2r-w&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=PUEMsou2r-w&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=PUEMsou2r-w'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=PUEMsou2r-w
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=PUEMsou2r-w
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=PUEMsou2r-w'
      title: an hour of page 14 (better version!)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Comics, Linocuts, Illustrations and joy from Stacie Arellano.'
purpose:
  - type: external
    url: 'http://www.redbubble.com/people/dreamling/shop'
    label: Buy Art Now!
  - type: external
    url: 'https://www.createspace.com/4959420'
    label: Buy my Graphic Novel!
github: true
author:
  name: Stacie Arellano
  email: stacie@staciearellano.com
  url: 'http://www.staciearellano.com'
