layout_spectrum: 0.2010923654495711
typography_spectrum: 0.14099364357382652
color:
  brandColors:
    - '#EED0B4'
    - '#9D8070'
    - '#2F1E14'
    - '#0D5C57'
    - '#5E9B89'
  brandStrength: 0.4497757881774687
  lightness: 0.09723640868523259
  saturation: 0.3733381445342583
  rhythmicContrast: 0.8012956641955615
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-78516-16
  facebook: null
  twitter: null
author:
  name: Stacie Arellano
  email: stacie@staciearellano.com
  url: 'http://www.staciearellano.com'
name: Ink Love
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Print shop
    url: 'https://squareup.com/store/staciearellano'
    type: external
  - name: Portraits
    id: a719412c-2d4d-4f94-b820-83d598a50386
    type: content
  - name: Linocuts
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
favicon: null
title: Ink Love
content: []
description: 'Comics, Linocuts, Illustrations and joy from Stacie Arellano.'
purpose:
  - type: external
    url: >-
      https://www.amazon.com/gp/product/1974167402/ref=as_li_tl?ie=UTF8&tag=quixotica&camp=1789&creative=9325&linkCode=as2&creativeASIN=1974167402&linkId=ae5ba45606544cc62e957ac02fe4c1bc
    label: Buy 'About Face' now!
  - type: external
    url: 'https://www.createspace.com/4959420'
    label: Buy Graphic Novel
