typography_spectrum: 0.16541457548737526
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.34538871608674526
  lightness: 0.2954148577991873
  saturation: 0.34013577178120613
  rhythmicContrast: 0.6912942116614431
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3209790391847491
analytics:
  google: null
  facebook: null
  twitter: null
name: Stacie Arellano - Portfolio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
  - name: Prints & Paintings
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
favicon: null
purpose: []
