layout_spectrum: 0.3550645524492985
typography_spectrum: 0.5314556066667901
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.4752703214062396
  lightness: 0.1625767229870884
  saturation: 0.248764036926487
  rhythmicContrast: 0.3146156326511709
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-78516-16
  facebook: null
  twitter: null
author:
  name: Stacie Arellano
  email: stacie@staciearellano.com
  url: 'http://www.staciearellano.com'
name: Ink Love
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Print shop
    url: 'https://squareup.com/store/staciearellano'
    type: external
  - name: Portraits
    id: a719412c-2d4d-4f94-b820-83d598a50386
    type: content
  - name: Linocuts
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
favicon: null
title: Ink Love
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/8220d6faafd207bc52cd3f6e21755b5b11df54c5.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/8220d6faafd207bc52cd3f6e21755b5b11df54c5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/70dd180bd386ddb15ad1a4acd92a390c/noop.jpg?input=https%3A%2F%2Fscontent-iad3-1.cdninstagram.com%2Fvp%2F7a2c8e4960520234aa0b2d0b988116dc%2F5B78FC69%2Ft51.2885-15%2Fe35%2F30933776_2093997707283961_7497686149058527232_n.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Comics, Linocuts, Illustrations and joy from Stacie Arellano.'
purpose:
  - type: external
    url: >-
      https://www.amazon.com/gp/product/1974167402/ref=as_li_tl?ie=UTF8&tag=quixotica&camp=1789&creative=9325&linkCode=as2&creativeASIN=1974167402&linkId=ae5ba45606544cc62e957ac02fe4c1bc
    label: Buy 'About Face' now!
  - type: external
    url: 'https://www.createspace.com/4959420'
    label: Buy Graphic Novel
