layout_spectrum: 0.4274959643332675
typography_spectrum: 0.2739528160964572
color:
  brandColors:
    - '#5E4C3E'
    - '#211A14'
    - '#7C7956'
    - '#F9D49F'
    - '#B2B387'
  brandStrength: 0.442700668151057
  lightness: 0.06031559048036095
  saturation: 0.3708198719052137
  rhythmicContrast: 0.8040788866860774
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-78516-16
  facebook: null
  twitter: null
author:
  name: Stacie Arellano
  email: stacie@staciearellano.com
  url: 'http://www.staciearellano.com'
name: Ink Love
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Print shop
    url: 'https://squareup.com/store/staciearellano'
    type: external
  - name: Portraits
    id: a719412c-2d4d-4f94-b820-83d598a50386
    type: content
  - name: Linocuts
    id: 54043675-246d-4d50-9319-ab387fe33c68
    type: content
  - name: Comics
    id: e93c2182-736c-4096-80a7-4a725988d154
    type: content
  - name: The Artist
    id: 6f8d5106-af04-4107-98fd-785e80adecce
    type: content
favicon: null
title: Ink Love
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/ce6304ca3deb6b53e118179035795b070c1d9fa0.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/ce6304ca3deb6b53e118179035795b070c1d9fa0.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/32502a8596fb6bb4e7e083d04145fc03/noop.jpg?input=https%3A%2F%2Fscontent-iad3-1.cdninstagram.com%2Ft51.2885-15%2Fs640x640%2Fsh0.08%2Fe35%2F22157778_1301220773339962_6163790089991225344_n.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/06b9669f-1c1b-4c45-894e-6548cf16bc1b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/06b9669f-1c1b-4c45-894e-6548cf16bc1b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Comics, Linocuts, Illustrations and joy from Stacie Arellano.'
purpose:
  - type: external
    url: >-
      https://www.amazon.com/gp/product/1974167402/ref=as_li_tl?ie=UTF8&tag=quixotica&camp=1789&creative=9325&linkCode=as2&creativeASIN=1974167402&linkId=ae5ba45606544cc62e957ac02fe4c1bc
    label: Buy 'About Face' now!
  - type: external
    url: 'https://www.createspace.com/4959420'
    label: Buy Graphic Novel
